version: "3.5"

services:

  api:
    container_name: payor-example-php
    build: .
    volumes:
      - ./lumen/app:/var/www/html/app
      - ./lumen/bootstrap:/var/www/html/bootstrap
      - ./lumen/database:/var/www/html/database
      - ./lumen/public:/var/www/html/public
      - ./lumen/resources:/var/www/html/resources
      - ./lumen/tests:/var/www/html/tests
      - ./lumen/.env:/var/www/html/.env
      - ./lumen/composer.json:/var/www/html/composer.json
      - ./lumen/composer.lock:/var/www/html/composer.lock
      - ./lumen/phpunit.xml:/var/www/html/phpunit.xml
    command: supervisord -c /etc/supervisord.conf
    ports:
      - "4567:80"
    networks:
      - payornetwork
    environment:
      APP_ENV: local
      APP_DEBUG: 'false'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: payor
      DB_USERNAME: payor
      DB_PASSWORD: payor
      CACHE_DRIVER: file
    depends_on:
      - db
      - redis

  db:
    image: mysql
    container_name: db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: payor
      MYSQL_DATABASE: payor
      MYSQL_USER: payor
      MYSQL_PASSWORD: payor
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - payornetwork

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis
    networks:
      - payornetwork

networks:
  payornetwork:
    name: external_payornetwork